# Generated by Django 2.1.4 on 2018-12-29 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realtor',
            name='lastname',
        ),
    ]
